apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: dXY1ZGllYXk2azJ0aWRvY2tlcg==
  azurestorageaccountkey: cG95U0pYY2FmQ3hsbHloRk4yV1Z0bUVhRjdWbUtFUWZLYjZIN2RnQkdEQllBL05zK25vNDN4M3ZPVkJPV294bitHTnEyVnhhVTJZa3BidFBvaEFyNHc9PQ==
